// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// heston_price_r
double heston_price_r(double S, double K, double T, double r, double v0, double kappa, double theta, double xi, double rho, int is_call);
RcppExport SEXP _Volaris_heston_price_r(SEXP SSEXP, SEXP KSEXP, SEXP TSEXP, SEXP rSEXP, SEXP v0SEXP, SEXP kappaSEXP, SEXP thetaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP is_callSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type is_call(is_callSEXP);
    rcpp_result_gen = Rcpp::wrap(heston_price_r(S, K, T, r, v0, kappa, theta, xi, rho, is_call));
    return rcpp_result_gen;
END_RCPP
}
// garch11_fit_r
List garch11_fit_r(NumericVector returns);
RcppExport SEXP _Volaris_garch11_fit_r(SEXP returnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type returns(returnsSEXP);
    rcpp_result_gen = Rcpp::wrap(garch11_fit_r(returns));
    return rcpp_result_gen;
END_RCPP
}
// garch11_variances_r
NumericVector garch11_variances_r(double omega, double alpha, double beta, NumericVector returns);
RcppExport SEXP _Volaris_garch11_variances_r(SEXP omegaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP returnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type returns(returnsSEXP);
    rcpp_result_gen = Rcpp::wrap(garch11_variances_r(omega, alpha, beta, returns));
    return rcpp_result_gen;
END_RCPP
}
// garch11_forecast_r
NumericVector garch11_forecast_r(double omega, double alpha, double beta, NumericVector returns, int h);
RcppExport SEXP _Volaris_garch11_forecast_r(SEXP omegaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP returnsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type returns(returnsSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(garch11_forecast_r(omega, alpha, beta, returns, h));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP r_binomial_price(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_bs_delta(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_bs_gamma(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_bs_price(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_bs_rho(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_bs_theta(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_bs_vega(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_gbm_paths(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_gbm_paths_antithetic(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_implied_vol(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_mc_price_asian(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_mc_price_barrier(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_mc_price_european(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_vol_close_to_close(SEXP, SEXP);
RcppExport SEXP r_vol_garman_klass(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP r_vol_parkinson(SEXP, SEXP, SEXP);
RcppExport SEXP r_vol_yang_zhang(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_Volaris_heston_price_r", (DL_FUNC) &_Volaris_heston_price_r, 10},
    {"_Volaris_garch11_fit_r", (DL_FUNC) &_Volaris_garch11_fit_r, 1},
    {"_Volaris_garch11_variances_r", (DL_FUNC) &_Volaris_garch11_variances_r, 4},
    {"_Volaris_garch11_forecast_r", (DL_FUNC) &_Volaris_garch11_forecast_r, 5},
    {"r_binomial_price",       (DL_FUNC) &r_binomial_price,        9},
    {"r_bs_delta",             (DL_FUNC) &r_bs_delta,              6},
    {"r_bs_gamma",             (DL_FUNC) &r_bs_gamma,              5},
    {"r_bs_price",             (DL_FUNC) &r_bs_price,              6},
    {"r_bs_rho",               (DL_FUNC) &r_bs_rho,                6},
    {"r_bs_theta",             (DL_FUNC) &r_bs_theta,              6},
    {"r_bs_vega",              (DL_FUNC) &r_bs_vega,               5},
    {"r_gbm_paths",            (DL_FUNC) &r_gbm_paths,             6},
    {"r_gbm_paths_antithetic", (DL_FUNC) &r_gbm_paths_antithetic,  6},
    {"r_implied_vol",          (DL_FUNC) &r_implied_vol,           6},
    {"r_mc_price_asian",       (DL_FUNC) &r_mc_price_asian,        8},
    {"r_mc_price_barrier",     (DL_FUNC) &r_mc_price_barrier,     11},
    {"r_mc_price_european",    (DL_FUNC) &r_mc_price_european,     7},
    {"r_vol_close_to_close",   (DL_FUNC) &r_vol_close_to_close,    2},
    {"r_vol_garman_klass",     (DL_FUNC) &r_vol_garman_klass,      5},
    {"r_vol_parkinson",        (DL_FUNC) &r_vol_parkinson,         3},
    {"r_vol_yang_zhang",       (DL_FUNC) &r_vol_yang_zhang,        5},
    {NULL, NULL, 0}
};

RcppExport void R_init_Volaris(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
