# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

heston_price_r <- function(S, K, T, r, v0, kappa, theta, xi, rho, is_call) {
    .Call('_Volaris_heston_price_r', PACKAGE = 'Volaris', S, K, T, r, v0, kappa, theta, xi, rho, is_call)
}

garch11_fit_r <- function(returns) {
    .Call('_Volaris_garch11_fit_r', PACKAGE = 'Volaris', returns)
}

garch11_variances_r <- function(omega, alpha, beta, returns) {
    .Call('_Volaris_garch11_variances_r', PACKAGE = 'Volaris', omega, alpha, beta, returns)
}

garch11_forecast_r <- function(omega, alpha, beta, returns, h) {
    .Call('_Volaris_garch11_forecast_r', PACKAGE = 'Volaris', omega, alpha, beta, returns, h)
}

