name: R CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          - {os: windows-latest}

    steps:

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: false
      
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install libgsl-dev libgomp1

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gsl libomp
          mkdir -p ~/.R
          echo "CPPFLAGS=-I$(brew --prefix gsl)/include -I$(brew --prefix libomp)/include -Xclang -fopenmp" >> ~/.R/Makevars
          echo "LDFLAGS=-L$(brew --prefix gsl)/lib -L$(brew --prefix libomp)/lib -lomp" >> ~/.R/Makevars

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: pacman -Sy --noconfirm mingw-w64-ucrt-x86_64-gsl

      - name: Install R packages
        run: Rscript -e "install.packages(c('Rcpp', 'testthat', 'knitr', 'rmarkdown'), repos='https://cloud.r-project.org')"

      - name: Fix line endings (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: find R/Volaris/src R/Volaris/R -type f | xargs sed -i 's/\r//'
        
      - name: R CMD check
        shell: bash
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          R CMD build --no-build-vignettes R/Volaris
          R CMD check --as-cran --no-manual --no-vignettes Volaris_*.tar.gz